# Understanding Homelessness Rates

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
<li><a href="#eda">Exploratory Data Analysis</a></li>
<li><a href="#conclusions">Conclusions</a></li>
</ul>

## Introduction
**Need to add info about the databases and assumptions of homelessness including personal v macro issues**

### Data Background
- Originally was going to use a dataset from Kaggle but decided to pull straight from HUD-CoC site. 
- Used [2007 - 2017 PIT Counts by State](https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/) and converted to single database

(borrowed from: https://www.kaggle.com/bltxr9/eda-of-total-homeless-population)
This dataset was generated by CoC and provided to HUD. Note: HUD did not conduct a full data quality review on the data submitted by each CoC.

What is the [Continuum of Care (CoC) Program](https://www.hudexchange.info/programs/coc/)?

Original Data: [PIT and HIC Data Since 2007](https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/)

CoC-HUD Summary Reports: [CoC Homeless Populations and Subpopulations Reports](https://www.hudexchange.info/programs/coc/coc-homeless-populations-and-subpopulations-reports/)

**Other Resources**

[Funding Awards](https://www.hudexchange.info/programs/coc/awards-by-component/)

[CoC Dashboard Reports](https://www.hudexchange.info/programs/coc/coc-dashboard-reports/)

[CoC Housing Inventory Count Reports](https://www.hudexchange.info/programs/coc/coc-housing-inventory-count-reports/)

## Data Wrangling

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Inspect Data

In [72]:
df = pd.read_csv('homeless-pit-by-state.csv')
df.head()

,State,Year,Number of CoCs,Total Homeless,Sheltered Homeless,Unsheltered Homeless,Homeless Individuals,Sheltered Homeless Individuals,Unsheltered Homeless Individuals,Homeless People in Families,...,Unsheltered Parenting Youth (Under 25),Parenting Youth Under 18,Sheltered Parenting Youth Under 18,Unsheltered Parenting Youth Under 18,Parenting Youth Age 18-24,Sheltered Parenting Youth Age 18-24,Unsheltered Parenting Youth Age 18-24,Children of Parenting Youth,Sheltered Children of Parenting Youth,Unsheltered Children of Parenting Youth
0,AK,2017,2,"1,845","1,551",294,"1,354","1,060",294,491,...,0,0,0,0,22,22,0,39,39,0
1,AL,2017,8,"3,793","2,656","1,137","2,985","1,950","1,035",808,...,3,6,6,0,23,20,3,39,35,4
2,AR,2017,6,"2,467","1,273","1,194","2,068",937,"1,131",399,...,0,0,0,0,10,10,0,13,13,0
3,AZ,2017,3,"8,947","5,781","3,166","6,488","3,423","3,065","2,459",...,0,0,0,0,81,81,0,112,112,0
4,CA,2017,43,"134,278","42,636","91,642","112,756","25,022","87,734","21,522",...,234,16,11,5,874,645,229,"1,058",782,276

#### Check Data Types and Missing Data

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 45 columns):
State                                                          605 non-null object
Year                                                           605 non-null int64
Number of CoCs                                                 605 non-null int64
Total Homeless                                                 605 non-null object
Sheltered Homeless                                             605 non-null object
Unsheltered Homeless                                           605 non-null object
Homeless Individuals                                           605 non-null object
Sheltered Homeless Individuals                                 605 non-null object
Unsheltered Homeless Individuals                               605 non-null object
Homeless People in Families                                    605 non-null object
Sheltered Homeless People in Families                          605 non-null object
Unsheltered Homeless People in Families                        605 non-null object
Chronically Homeless                                           605 non-null object
Sheltered Chronically Homeless                                 605 non-null object
Unsheltered Chronically Homeless                               605 non-null object
Chronically Homeless Individuals                               605 non-null object
Sheltered Chronically Homeless Individuals                     605 non-null object
Unsheltered Chronically Homeless Individuals                   605 non-null object
Chronically Homeless People in Families                        385 non-null object
Sheltered Chronically Homeless People in Families              385 non-null object
Unsheltered Chronically Homeless People in Families            385 non-null object
Homeless Veterans                                              385 non-null object
Sheltered Homeless Veterans                                    385 non-null object
Unsheltered Homeless Veterans                                  385 non-null object
Homeless Unaccompanied Youth (Under 25)                        165 non-null object
Sheltered Homeless Unaccompanied Youth (Under 25)              165 non-null object
Unsheltered Homeless Unaccompanied Youth (Under 25)            165 non-null object
Homeless Unaccompanied Children (Under 18)                     165 non-null object
Sheltered Homeless Unaccompanied Children (Under 18)           165 non-null object
Unsheltered Homeless Unaccompanied Children (Under 18)         165 non-null object
Homeless Unaccompanied Young Adults (Age 18-24)                165 non-null object
Sheltered Homeless Unaccompanied Young Adults (Age 18-24)      165 non-null object
Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)    165 non-null object
Parenting Youth (Under 25)                                     165 non-null object
Sheltered Parenting Youth (Under 25)                           165 non-null object
Unsheltered Parenting Youth (Under 25)                         165 non-null object
Parenting Youth Under 18                                       165 non-null object
Sheltered Parenting Youth Under 18                             165 non-null object
Unsheltered Parenting Youth Under 18                           165 non-null object
Parenting Youth Age 18-24                                      165 non-null object
Sheltered Parenting Youth Age 18-24                            165 non-null object
Unsheltered Parenting Youth Age 18-24                          165 non-null object
Children of Parenting Youth                                    165 non-null object
Sheltered Children of Parenting Youth                          165 non-null object
Unsheltered Children of Parenting Youth                        165 non-null object
dtypes: int64(2), object(43)
memory usage: 212.8+ KB

_Observations_
- Missing data is consistent across groups of categories. Visual inspection of data confirms that this is due to additional categories added in subsequent years. 
- Data is all in object format and will need to be converted to int. 
- Not all categories are multually exclusive, confirmation is required to confirm how data is summed.

Visualization of data that all columns are available from 2015 onwards, 2011 - 2014 contains columns up to Unsheltered Homeless Veterans and 2007 - 2013 contains columns up to Unsheltered Chronically Homeless Individuals.

#### Check unique values

In [12]:
df.nunique()

State                                                           56
Year                                                            11
Number of CoCs                                                  34
Total Homeless                                                 577
Sheltered Homeless                                             570
Unsheltered Homeless                                           523
Homeless Individuals                                           573
Sheltered Homeless Individuals                                 560
Unsheltered Homeless Individuals                               520
Homeless People in Families                                    558
Sheltered Homeless People in Families                          550
Unsheltered Homeless People in Families                        378
Chronically Homeless                                           522
Sheltered Chronically Homeless                                 461
Unsheltered Chronically Homeless                               445
Chronically Homeless Individuals                               501
Sheltered Chronically Homeless Individuals                     460
Unsheltered Chronically Homeless Individuals                   386
Chronically Homeless People in Families                        230
Sheltered Chronically Homeless People in Families              178
Unsheltered Chronically Homeless People in Families            131
Homeless Veterans                                              317
Sheltered Homeless Veterans                                    316
Unsheltered Homeless Veterans                                  219
Homeless Unaccompanied Youth (Under 25)                        152
Sheltered Homeless Unaccompanied Youth (Under 25)              138
Unsheltered Homeless Unaccompanied Youth (Under 25)            114
Homeless Unaccompanied Children (Under 18)                      88
Sheltered Homeless Unaccompanied Children (Under 18)            77
Unsheltered Homeless Unaccompanied Children (Under 18)          41
Homeless Unaccompanied Young Adults (Age 18-24)                150
Sheltered Homeless Unaccompanied Young Adults (Age 18-24)      134
Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)    112
Parenting Youth (Under 25)                                     117
Sheltered Parenting Youth (Under 25)                           117
Unsheltered Parenting Youth (Under 25)                          34
Parenting Youth Under 18                                        15
Sheltered Parenting Youth Under 18                              15
Unsheltered Parenting Youth Under 18                             6
Parenting Youth Age 18-24                                      111
Sheltered Parenting Youth Age 18-24                            114
Unsheltered Parenting Youth Age 18-24                           35
Children of Parenting Youth                                    121
Sheltered Children of Parenting Youth                          127
Unsheltered Children of Parenting Youth                         41
dtype: int64

_Observations_
- There are 11 years of data contained in the set (2007 - 2017)
- Need to confirm what states are covered within state

In [13]:
df['State'].unique()

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD',
       'ME', 'MI', 'MN', 'MO', 'MP', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC',
       'SD', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY',
       'KS*'], dtype=object)

- It appears that the list includes some US territories and DC. I am less familiar with state abbreviations - will need to get state names for reference.
- One of states is KS*, note from dataset says: The number of CoCs in 2017 was 399. However, MO-604 merged in 2016 and covers territory in both MO and KS, contributing to the PIT count in both states. This will need to be inspected individually to understand.

### Clean Data

In [64]:
df.columns

Index(['State', 'Year', 'Number of CoCs', 'Total Homeless',
       'Sheltered Homeless', 'Unsheltered Homeless', 'Homeless Individuals',
       'Sheltered Homeless Individuals', 'Unsheltered Homeless Individuals',
       'Homeless People in Families', 'Sheltered Homeless People in Families',
       'Unsheltered Homeless People in Families', 'Chronically Homeless',
       'Sheltered Chronically Homeless', 'Unsheltered Chronically Homeless',
       'Chronically Homeless Individuals',
       'Sheltered Chronically Homeless Individuals',
       'Unsheltered Chronically Homeless Individuals',
       'Chronically Homeless People in Families',
       'Sheltered Chronically Homeless People in Families',
       'Unsheltered Chronically Homeless People in Families',
       'Homeless Veterans', 'Sheltered Homeless Veterans',
       'Unsheltered Homeless Veterans',
       'Homeless Unaccompanied Youth (Under 25)',
       'Sheltered Homeless Unaccompanied Youth (Under 25)',
       'Unsheltered Homeless Unaccompanied Youth (Under 25)',
       'Homeless Unaccompanied Children (Under 18)',
       'Sheltered Homeless Unaccompanied Children (Under 18)',
       'Unsheltered Homeless Unaccompanied Children (Under 18)',
       'Homeless Unaccompanied Young Adults (Age 18-24)',
       'Sheltered Homeless Unaccompanied Young Adults (Age 18-24)',
       'Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)',
       'Parenting Youth (Under 25)', 'Sheltered Parenting Youth (Under 25)',
       'Unsheltered Parenting Youth (Under 25)', 'Parenting Youth Under 18',
       'Sheltered Parenting Youth Under 18',
       'Unsheltered Parenting Youth Under 18', 'Parenting Youth Age 18-24',
       'Sheltered Parenting Youth Age 18-24',
       'Unsheltered Parenting Youth Age 18-24', 'Children of Parenting Youth',
       'Sheltered Children of Parenting Youth',
       'Unsheltered Children of Parenting Youth'],
      dtype='object')

In [66]:
df['Year'] = df['Year'].astype(int)

In [68]:
df['Number of CoCs'] = df['Number of CoCs'].astype(int)

In [80]:
df['Total Homeless'] = df['Total Homeless'].apply(lambda x: x.replace(',', '')).astype(float)

ValueError: could not convert string to float: '.'

In [78]:
string = 'sdfs0sdfs0'
string.replace('0', '')

'sdfssdfs'